name: szyszka # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Szyszka - very fast file renamer written in Rust # 79 char long summary
description: |
  Szyszka is very fast file renamer.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  szyszka:
    plugin: nil
    source: https://github.com/qarmin/szyszka.git
    build-packages:
      - libgtk-3-dev
      - curl
      - gcc
      - git
    stage-packages:
      - libgtk-3-dev

apps:
  szyszka:
    command: bin/szyszka
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - udisks2
